# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'PData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'

  # Pods for PData

  target 'PDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PDataUITests' do
    # Pods for testing
  end

end
